FROM python:3.12 AS base
RUN \
  --mount=type=cache,target=/var/cache/apt,sharing=locked \
  --mount=type=cache,target=/var/lib/apt,sharing=locked \
  --mount=type=cache,target=/root/.distrib/rust,sharing=locked \
  --mount=type=cache,target=/root/.cache/pip,sharing=locked \
  dd if=/dev/random of="/var/cache/apt/CACHED" bs=4k iflag=fullblock,count_bytes count=1M && \
  dd if=/dev/random of="/var/lib/apt/CACHED" bs=4k iflag=fullblock,count_bytes count=2M && \
  dd if=/dev/random of="/root/.distrib/rust/CACHED" bs=4k iflag=fullblock,count_bytes count=3M && \    
  dd if=/dev/random of="/root/.cache/pip/CACHED" bs=4k iflag=fullblock,count_bytes count=4M   