#!/bin/bash
set -euo pipefail

# prepare static bin packages in dist
# expects staticx installed dependencies
# required params: version plat

staticx --loglevel INFO dist/icloudpd-$1-linux-$2 dist/icloudpd-$1-linux-$2.static
staticx --loglevel INFO dist/icloud-$1-linux-$2 dist/icloud-$1-linux-$2.static
staticx --loglevel INFO dist/icloudpd-ex-$1-linux-$2 dist/icloudpd-ex-$1-linux-$2.static

# make static default
mv dist/icloudpd-$1-linux-$2.static dist/icloudpd-$1-linux-$2
mv dist/icloud-$1-linux-$2.static dist/icloud-$1-linux-$2
mv dist/icloudpd-ex-$1-linux-$2.static dist/icloudpd-ex-$1-linux-$2

chmod 755 dist/icloudpd-$1-linux-$2
chmod 755 dist/icloud-$1-linux-$2
chmod 755 dist/icloudpd-ex-$1-linux-$2

