#!/bin/bash
set -euo pipefail

# prepare bin packages in dist
# expects python with installed dependencies
# required params: version plat

pyinstaller --collect-all keyrings.alt --hidden-import pkgutil --collect-all tzdata --onefile src/starters/icloudpd.py src/starters/icloud.py --name icloudpd-$1-linux-$2.dynamic
pyinstaller --collect-all keyrings.alt --hidden-import pkgutil --collect-all tzdata --onefile src/starters/icloud.py --name icloud-$1-linux-$2.dynamic
pyinstaller --collect-all keyrings.alt --hidden-import pkgutil --collect-all tzdata --onefile src/starters/icloudpd_ex.py --name icloudpd-ex-$1-linux-$2.dynamic

cp -f dist/icloudpd-$1-linux-$2.dynamic dist/icloudpd-$1-linux-$2
cp -f dist/icloud-$1-linux-$2.dynamic dist/icloud-$1-linux-$2
cp -f dist/icloudpd-ex-$1-linux-$2.dynamic dist/icloudpd-ex-$1-linux-$2


staticx --loglevel INFO dist/icloudpd-$1-linux-$2 dist/icloudpd-$1-linux-$2.static
staticx --loglevel INFO dist/icloud-$1-linux-$2 dist/icloud-$1-linux-$2.static
staticx --loglevel INFO dist/icloudpd-ex-$1-linux-$2 dist/icloudpd-ex-$1-linux-$2.static

mv -f dist/icloudpd-$1-linux-$2.static dist/icloudpd-$1-linux-$2
mv -f dist/icloud-$1-linux-$2.static dist/icloud-$1-linux-$2
mv -f dist/icloudpd-ex-$1-linux-$2.static dist/icloudpd-ex-$1-linux-$2

chmod 755 dist/icloudpd-$1-linux-$2
chmod 755 dist/icloud-$1-linux-$2
chmod 755 dist/icloudpd-ex-$1-linux-$2