#!/bin/bash
set -euo pipefail

# prepare bin packages in dist
# expects python with installed dependencies
# required params: version arch

PYTHONHASHSEED=42 pyinstaller --collect-all keyrings.alt --copy-metadata keyrings.alt --hidden-import pkg_resources.extern --hidden-import pkgutil --collect-all tzdata --add-data "src/icloudpd/server/static:static" --add-data "src/icloudpd/server/templates:templates" --onefile src/starters/icloudpd.py src/starters/icloud.py --name icloudpd-$1-macos-$2
PYTHONHASHSEED=42 pyinstaller --collect-all keyrings.alt --copy-metadata keyrings.alt --hidden-import pkg_resources.extern --hidden-import pkgutil --collect-all tzdata --add-data "src/icloudpd/server/static:static" --add-data "src/icloudpd/server/templates:templates" --onefile src/starters/icloud.py --name icloud-$1-macos-$2
PYTHONHASHSEED=42 pyinstaller --collect-all keyrings.alt --copy-metadata keyrings.alt --hidden-import pkg_resources.extern --hidden-import pkgutil --collect-all tzdata --add-data "src/icloudpd/server/static:static" --add-data "src/icloudpd/server/templates:templates" --onefile src/starters/icloudpd_ex.py --name icloudpd-ex-$1-macos-$2
