#!/bin/bash
set -euo pipefail

# realpath not availabe on Mac by default...
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

CURRENT_DIR=$(dirname "$0")
ROOT_DIR="$(realpath $(dirname "$0")/..)"

ICLOUDPD_VERSION="$(cat "$ROOT_DIR/setup.py" | grep version= | cut -d'"' -f 2)"
echo "Current icloudpd version: ${ICLOUDPD_VERSION}"

docker build \
  -t "icloudpd/icloudpd:${ICLOUDPD_VERSION}" \
  -f "Dockerfile.release" \
  --build-arg ICLOUDPD_VERSION=${ICLOUDPD_VERSION} \
  "$ROOT_DIR"

docker tag "icloudpd/icloudpd:${ICLOUDPD_VERSION}" "icloudpd/icloudpd:${ICLOUDPD_VERSION}-alpine"
docker tag "icloudpd/icloudpd:${ICLOUDPD_VERSION}" "icloudpd/icloudpd:latest"
