#!/usr/bin/env python3
""" takes results of compatibility tests and compie into one file """

import os
import sys
import itertools

def matrix(files):
    archs = [k for k, _ in itertools.groupby(sorted(files, key = lambda ft: ft[3]), key = lambda ft: ft[3])]
    # caption
    print('|'.join(["oses and dist"] + archs))
    print('---')

    oses = [k for k, _ in itertools.groupby(sorted(files, key = lambda ft: ft[2]), key = lambda ft: ft[2])]
    for o in oses:
        results_raw = [list(filter(lambda ft: ft[2] == o and ft[3] == a, files)) for a in archs]
        results = ["N/A" if len(r) == 0 else r[0][4] for r in results_raw]
        print('|'.join([o] + results))

def main():
    """ param: folder """
    files = [[os.path.getsize(f)] + f.split('.') for f in os.listdir(sys.argv[1] if len(sys.argv) > 1 else ".") if os.path.isfile(f) and len(f.split('.')) == 4]
    print("# Minimal Effort Compatibility")
    groups = [(k, list(g)) for k, g in itertools.groupby(sorted(files, key = lambda ft: ft[1]), key = lambda ft: ft[1])]
    for (g, f) in groups: 
        print(f"## {g}")
        matrix(f)

if __name__ == "__main__":
    main()