#!/bin/bash
set -euo pipefail

# dev script
# expecting dist/binary_dist to be set
# required param registry_url
#
# prereq
# disable auth on pypi server
#
# cleint use: pip install --index http://192.168.1.20:4880 --trusted-host 192.168.1.20 icloudpd

# linux
twine upload --repository-url $1 --non-interactive -u bogus -p bogus dist/icloudpd-1.17.3-py2.py3-none-manylinux*.whl dist/icloudpd-1.17.3-py2.py3-none-macos*.whl dist/icloudpd-1.17.3-py2.py3-none-win*.whl dist/icloudpd-1.17.3-py3-none-any.whl
