#!/bin/bash
set -euo pipefail

# realpath not available on Mac by default...
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

CURRENT_DIR=$(dirname "$0")
ROOT_DIR="$(realpath $(dirname "$0")/..)"

$CURRENT_DIR/format
$CURRENT_DIR/lint
$CURRENT_DIR/type_check
$CURRENT_DIR/test
