#!/usr/bin/env bash
set -euo pipefail
echo "Running mypy..."
python3 -m mypy src tests --strict --python-version 3.10
# --strict-equality --warn-return-any --disallow-any-generics --disallow-untyped-defs --disallow-untyped-calls --check-untyped-defs
