#!/bin/bash
set -euo pipefail
echo "Running mypy..."
python3 -m mypy src tests --strict-equality --warn-return-any
# too strict now: --disallow-any-generics --disallow-untyped-defs --disallow-untyped-calls 