name: "Render docs"

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: docker/setup-buildx-action@v3
      id: setup

    - name: Cache Build
      uses: actions/cache@v4
      id: cache
      with:
        # if the list or anything in these folders expected to change, then cache needs to be cleared and rebuilt, because it is keyed only by pyproject.toml hash
        path: .cache
        key: build-doc-${{ hashFiles('pyproject.toml','Dockerfile.build-doc') }}
        restore-keys: |
          build-doc-
      
    - name: Create folders on cache miss
      run: |
        mkdir -p .cache/var/cache/apt
        mkdir -p .cache/var/lib/apt
        mkdir -p .cache/root/.cache/pip
        mkdir -p .cache/root/.distrib/rust
        mkdir -p .cache/root/.cargo/registry
      
    - name: Inject docker cache
      uses: reproducible-containers/buildkit-cache-dance@v3.1.2
      with:
        cache-map: |
          {
            ".cache/var/cache/apt": "/var/cache/apt",
            ".cache/var/lib/apt": "/var/lib/apt",
            ".cache/root/.cache/pip": "/root/.cache/pip",
            ".cache/root/.cargo/registry": "/root/.cargo/registry",
            ".cache/root/.distrib/rust": "/root/.distrib/rust"
          }

    - name: Build Doc
      uses: docker/build-push-action@v6
      with:
        push: false
        platforms: linux/arm64
        # do not cache layers
        file: Dockerfile.build-doc
        outputs: type=local,dest=docs/_build/html
        provenance: false
        context: .

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/
         
