name: "Render docs"

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install Dev dependencies
      run: |
        pip3 install --disable-pip-version-check -e .[dev]

    - name: Build HTML
      run: |
        sphinx-build docs docs/_build/html

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/
         
