name: Promote Snap (candidate -> stable)

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Promote snap to stable
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_TOKEN }}
        run: |
          sudo snap install --classic snapcraft
          snapcraft promote icloudpd --from-channel latest/candidate --to-channel latest/stable --yes
